<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_29</name>
   <tag></tag>
   <elementGuidId>9519028c-a565-426e-a846-6edd79ed2bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='addattmonitoring']/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div[2]/div[5]/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-datepicker__day.react-datepicker__day--sat.react-datepicker__day--keyboard-selected.react-datepicker__day--today.react-datepicker__day--weekend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1095450a-ebf0-49ab-9f2f-15b250ececd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__day react-datepicker__day--sat react-datepicker__day--keyboard-selected react-datepicker__day--today react-datepicker__day--weekend</value>
      <webElementGuid>8bfd8a66-3ec7-4aa8-9610-11d93f5d64a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>day-29</value>
      <webElementGuid>04c39579-294f-4170-812f-41ae74be675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d0608598-0c45-4dcf-9883-bb32b2fb3c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>1dc15bf4-81dd-4de5-81ea-2d6156ffc7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addattmonitoring&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-md-8 col-lg-8 col-xl-8&quot;]/div[@class=&quot;form__form-group&quot;]/div[@class=&quot;form__form-group-field&quot;]/div[@class=&quot;w-100 row&quot;]/div[@class=&quot;col-sm-12 col-md-8&quot;]/div[@class=&quot;form__form-group-field form-group-ml-pl-0 w-100&quot;]/div[@class=&quot;date-picker&quot;]/div[@class=&quot;form__form-group-input-wrap form__form-group-input-wrap--error-above&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__month&quot;]/div[@class=&quot;react-datepicker__week&quot;]/div[@class=&quot;react-datepicker__day react-datepicker__day--sat react-datepicker__day--keyboard-selected react-datepicker__day--today react-datepicker__day--weekend&quot;]</value>
      <webElementGuid>4aedefe4-53f9-4cd5-a933-db5e44355620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addattmonitoring']/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div[2]/div[5]/div[7]</value>
      <webElementGuid>f2af4e99-f3a1-48bd-880e-42b119bf8ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[41]</value>
      <webElementGuid>cb3d31fd-4cb4-4e39-8f74-06296e4f025b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::div[42]</value>
      <webElementGuid>0696952f-1064-4bbc-aef7-ff550507b08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Amount'])[1]/preceding::div[10]</value>
      <webElementGuid>4fb765f4-6965-4eb0-9a6c-80021664851e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::div[15]</value>
      <webElementGuid>1e3d6a57-6fce-498b-abb6-f1e1643f8b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]</value>
      <webElementGuid>9b791c30-4d6a-4614-b528-3d7182fb651f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '29' or . = '29')]</value>
      <webElementGuid>7c173c6c-1902-4fcf-acb1-d976be17851b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
