<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_July</name>
   <tag></tag>
   <elementGuidId>ec16d2dc-82bc-4b2f-8876-2e969e9d8fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='addattmonitoring']/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.react-datepicker__month-read-view--selected-month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72d6d6b6-a31e-4a8c-b4f5-bfb990be60dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__month-read-view--selected-month</value>
      <webElementGuid>6ec400fa-14e7-4801-a203-7088f277c76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>July</value>
      <webElementGuid>6f82448d-ca95-43e0-92e7-92094f72e91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addattmonitoring&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-md-8 col-lg-8 col-xl-8&quot;]/div[@class=&quot;form__form-group&quot;]/div[@class=&quot;form__form-group-field&quot;]/div[@class=&quot;w-100 row&quot;]/div[@class=&quot;col-sm-12 col-md-8&quot;]/div[@class=&quot;form__form-group-field form-group-ml-pl-0 w-100&quot;]/div[@class=&quot;date-picker&quot;]/div[@class=&quot;form__form-group-input-wrap form__form-group-input-wrap--error-above&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__header&quot;]/div[@class=&quot;react-datepicker__header__dropdown react-datepicker__header__dropdown--scroll&quot;]/div[@class=&quot;react-datepicker__month-dropdown-container react-datepicker__month-dropdown-container--scroll&quot;]/div[@class=&quot;react-datepicker__month-read-view&quot;]/span[@class=&quot;react-datepicker__month-read-view--selected-month&quot;]</value>
      <webElementGuid>5ddbef30-2f51-45a3-b40d-8fdbf8ab915f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addattmonitoring']/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/span[2]</value>
      <webElementGuid>4580d627-7c69-48a9-b503-d338d766c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 2023'])[1]/following::span[2]</value>
      <webElementGuid>92ffb8bd-0348-4abb-84f1-eb9d15bfda9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next month'])[1]/following::span[2]</value>
      <webElementGuid>b6b170ec-1d54-43ce-b80a-183fb17bcb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::span[3]</value>
      <webElementGuid>7a3e055f-ec18-4778-b2ed-d75671347e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::span[3]</value>
      <webElementGuid>c6bfe2b7-0eaf-4591-be16-6adca47a5b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='July']/parent::*</value>
      <webElementGuid>802578bf-ca3b-4985-a7ce-0812c161b05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>4360dc2e-8c47-4378-b54f-c90368a37f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'July' or . = 'July')]</value>
      <webElementGuid>6f42b46c-ff95-4738-be7e-0f9dd59186e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
